language: node_js
node_js:
- '6'
deploy:
  provider: npm
  email: contacto@platan.us
  api_key:
    secure: IJbM/cPv3F0Nv66nyMbaHWCwpb4FxiP3zjNWKxSSAjnB6U58vf4psAqsr85hk/7sc7hbHduE8a6QjKReTpxKCNsc5e5vDDGnGAWy00+x/n4PV40zUpLd+n40nnCiD2tX626/k/ZahH7FYhUlOqb2qX8F6yz8ULnJHJX5fxX7yyJQNXN/KA0NGO8QppbY2qEGgMDjd9xgwDOHhwUNkRfH9Tb0wBWioQldqaXL+MX1ii4baW8s3rlbliOpabJ62Wol45Rb7HtzoGVvYQK0YdewI4NfeI8OdkQ+Z6ZZp36LZn+JEoD3mTYMQ4kH7aB0vnkE8yhkn6ZV+TTtWI+6fv9wGCD34LI14FpJSAIZI42nHoDJtL2HNIWoZD44l2TcNhd7uJmCJXv/t3ytuXsSqZvyxiJGWho3/GqJ8LsCr6djy8FAHMcN2hUNzCjS9OYd/0NUFlZTzQW4biSK96b9uCbHoPFK+9z+6t9BPff29ifPXnFSNzqDeAOAUcJg5lKErUZVgNayMpzCUsMMRAQQtHf2hkfRa85jQu3ccKRZ0jBlZ0qlI/7OzGSL5ezeU54NuWQ6cq5ONzV2UKe0baqkgQhM4jKt+dbQPHNT3lXfRhKEXc87JMAokeSkTw/8fO1BJJKgUNggt1H6D9tmMuEcIVxwtl3emudgOkkVmuVVmzTW/Ug=
  on:
    tags: true
    repo: platanus/generator-pl-ionic
